### ISSUE TITLE
Where is the ‘user_data’ folder? I can't find it.

### ISSUE THREAD

**Issue by NGC2237-MyRose** [jerichooconnell/fastcat#21]
It seems that I need to load the files in the 'test_data' folder when using the 'phantom.return_projs(kernel,s,angles,mgy = 8, ASG=True,scat_on=False,det_on=False,bowtie=True, filter='bowtie_real', load_proj=True, proj_file='xcat_phan_mandible_180_no_amalgam')', but I can't find it.

**Comment by jerichooconnell** [comment]
Sorry! It looks like I messed with that file and pushed it to the repo by accident.

This highlights some features of fastcat, namely that you can use XCAT phantoms, however I don't put them in the repository since they are not open source and that would violate the licensing agreement. Also, that you can save a simulation to user_data and load it back if you want to make modifications that do not modify the primary projections but only modify the weighting of the primary projections, i.e. extra filtration, different detector etc. 

I committed a new version of the file that uses a Catphan phantom instead, should work now.
